home_page:
  title: Numerical Methods and Scientific Computing
  methods:
    - trapezoidal
    - midpoint
    - simpson
    - romberg
  integration_calc_backend_url: https://numerical-methods-and-scientific-9xca.onrender.com/api/v1/integrate